{{- $machinesetname := printf "%s-windows-worker-%s" .Values.infrastructureID .Values.zone -}}
{{- $privatesubnetname := printf "%s-private-%s" .Values.infrastructureID .Values.zone -}}
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureID }}
  name: {{ $machinesetname }}
  namespace: openshift-machine-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureID }}
      machine.openshift.io/cluster-api-machineset: {{ $machinesetname }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/os-id: Windows
        machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureID }}
        machine.openshift.io/cluster-api-machineset: {{ $machinesetname }}
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: {{ .Values.ami }}
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.infrastructureID }}-worker-profile
          instanceType: m5a.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: {{ .Values.zone }}
            region: {{ .Values.region }}
          securityGroups:
            - filters:
              - name: tag:Name
                values:
                  - {{ .Values.infrastructureID }}-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
                - {{ $privatesubnetname }}
          tags:
            - name: kubernetes.io/cluster/{{ .Values.infrastructureID }}
              value: owned
          userDataSecret:
            name: windows-user-data
            namespace: openshift-machine-api