{
 "title": "Windows Node Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_cpu_time_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * sum(rate(windows_cpu_time_total{instance='$server',mode != 'idle'}[5m])) / count(windows_cpu_core_frequency_mhz{instance='$server'})"
    }
   ]
  },
  {
   "title": "Physical Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "100* (windows_cs_physical_memory_bytes{instance='$server'} - windows_os_physical_memory_free_bytes{instance='$server'}) / windows_cs_physical_memory_bytes{instance='$server'}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "100 * (rate(windows_net_bytes_total{instance='$server'}[5m])) * 8 /  windows_net_current_bandwidth{instance='$server'}",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 * (windows_logical_disk_size_bytes{instance='$server'} - windows_logical_disk_free_bytes{instance='$server'}) /  windows_logical_disk_size_bytes{instance='$server'}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(time() - windows_system_system_up_time{instance='$server'}) "
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(windows_cpu_core_frequency_mhz{instance='$server'})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance='$server'}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "windows_net_current_bandwidth{instance='$server'}",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance='$server'}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_system_threads{instance='$server'}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_os_processes{instance='$server'}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 9 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Memory",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "CPU Usage by Mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * avg by (mode) (rate(windows_cpu_time_total{instance='$server'}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100* (windows_cs_physical_memory_bytes{instance='$server'} - windows_os_physical_memory_free_bytes{instance='$server'}) / windows_cs_physical_memory_bytes{instance='$server'}",
     "legendFormat": "Physical Memory"
    },
    {
     "expr": "100 * (windows_os_virtual_memory_bytes{instance='$server'} - windows_os_virtual_memory_free_bytes{instance='$server'}) / windows_os_virtual_memory_bytes{instance='$server'}",
     "legendFormat": "Vitual Memory"
    }
   ]
  },
  {
   "title": "CPU Usage by Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (core) (rate(windows_cpu_time_total{instance='$server',mode != 'idle'}[5m]))",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes{instance='$server'}",
     "legendFormat": "Pysical Mem"
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{instance='$server'}",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Disk Usage by Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (windows_logical_disk_size_bytes{instance='$server'} - windows_logical_disk_free_bytes{instance='$server'}) / windows_logical_disk_size_bytes{instance='$server'}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_reads_total{instance='$server'}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{instance='$server'}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Reqs Queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_requests_queued{instance='$server'}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Free Disk by Volume",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance='$server'}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_writes_total{instance='$server'}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{instance='$server'}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Ops Splitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(windows_logical_disk_split_ios_total{instance='$server'}[5m])",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Network Inbound Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(windows_net_packets_received_errors{instance='$server'}[5m]) / (rate(windows_net_packets_received_errors{instance='$server'}[5m]) + rate(windows_net_packets_received_total{instance='$server'}[5m]))",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Outbound Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(windows_net_packets_outbound_errors{instance='$server'}[5m]) / (rate(windows_net_packets_outbound_errors{instance='$server'}[5m]) + rate(windows_net_packets_sent_total{instance='$server'}[5m]))",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Inbound Discard Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(windows_net_packets_received_discarded{instance='$server'}[5m]) / (rate(windows_net_packets_received_discarded{instance='$server'}[5m]) + rate(windows_net_packets_received_total{instance='$server'}[5m]))",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Outbound Discard Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(windows_net_packets_outbound_discarded{instance='$server'}[5m]) / (rate(windows_net_packets_outbound_discarded{instance='$server'}[5m]) + rate(windows_net_packets_sent_total{instance='$server'}[5m]))",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Bandwidth Usage by Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (rate(windows_net_bytes_total{instance='$server'}[5m])) * 8 /  windows_net_current_bandwidth{instance='$server'}",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Received IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_packets_received_total{instance='$server'}[5m])",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Received Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance='$server'}[5m])",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Bandwidth Free by Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "windows_net_current_bandwidth{instance='$server'} - ((rate(windows_net_bytes_total{instance='$server'}[5m])) * 8) ",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Sent IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_packets_sent_total{instance='$server'}[5m])",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network Sent Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(windows_net_bytes_sent_total{instance='$server'}[5m])",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "content": "\n# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n\n\n\n"
  },
  {
   "title": "Processes and Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_os_processes{instance='$server'}",
     "legendFormat": "Processes"
    },
    {
     "expr": "windows_system_threads{instance='$server'}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Processor Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_system_processor_queue_length{instance='$server'}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "title": "Pagination Usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (windows_os_paging_limit_bytes{instance='$server'} - windows_os_paging_free_bytes{instance='$server'}) / windows_os_paging_limit_bytes{instance='$server'}",
     "legendFormat": "Pagination"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_os_users{instance='$server'}",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(windows_system_context_switches_total{instance='$server'}[5m])",
     "legendFormat": "Switches"
    }
   ]
  },
  {
   "title": "Free Pagination ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_os_paging_free_bytes{instance='$server'}",
     "legendFormat": "Pagination"
    }
   ]
  }
 ]
}