- name: create windows machine config operator namespace
  kubernetes.core.k8s:
    state: present
    apply: true
    validate_certs: false
    resource_definition: "{{ lookup('template', './templates/namespace.yaml.j2') | from_yaml }}"

- name: create the operator group
  kubernetes.core.k8s:
    state: present
    apply: true
    validate_certs: false
    resource_definition: "{{ lookup('template', './templates/operatorgroup.yaml.j2') | from_yaml }}"

- name: install wmco
  kubernetes.core.k8s:
    state: present
    apply: true
    validate_certs: false
    resource_definition: "{{ lookup('template', './templates/wmco.yaml.j2') | from_yaml }}"

- name: wait for wmco to be ready
  kubernetes.core.k8s_info:
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    namespace: "{{ namespace }}"
  register: __wmco_operator_install_result
  until: "(__wmco_operator_install_result['resources'][0]['status']['phase'] is defined) and (__wmco_operator_install_result['resources'][0]['status']['phase'] == 'Succeeded')"
  retries: 15
  delay: 15
  
- name: create secret which will contain the private key that WMCO can use to auth with windows node
  kubernetes.core.k8s:
    state: present
    apply: true
    validate_certs: false
    resource_definition: "{{ lookup('template', './templates/secret.yaml.j2') | from_yaml }}"