apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-windows-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  #encrypted: "true"
