- name: add windows worker nodes to openshift cluster
  hosts: localhost
  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml
                    
    - name: install WMCO
      include_tasks: ./tasks/enable-wmco.yaml

    - name: add windows worker nodes to cluster
      include_tasks: ./tasks/add-windows-workers.yaml
