- name: add windows worker nodes to openshift cluster
  hosts: localhost
  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: login to cluster
      community.okd.openshift_auth:
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ apiserver }}"
        validate_certs: false
      register: ocp_auth_results

    - name: write the api key to dynamic vars
      copy:
        content: "api_key: {{ ocp_auth_results.openshift_auth.api_key | to_nice_yaml }}"
        dest: "vars/dynamic/main.yaml"

    - name: import dynamic var data
      include_vars:
        dir: ./vars/dynamic
        ignore_unknown_extensions: True
        extensions:
          - yaml
          
    - name: install WMCO
      include_tasks: ./tasks/enable-wmco.yaml

    - name: add windows worker nodes to cluster
      include_tasks: ./tasks/add-windows-workers.yaml
